# vi: set ft=ruby :
# frozen_string_literal: false

# Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'
  config.vm.box_url = 'https://app.vagrantup.com/generic/boxes/ubuntu2004'
  config.vm.box_version = '3.6.10'
  config.vm.box_check_update = false
  config.vm.hostname = 'virt-remnux'

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  # shares
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 4, nfs_udp: false

  config.vagrant.plugins = ['vagrant-reload', { 'vagrant-libvirt' => { 'version' => '^0.6.2' } }]

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.default_prefix = 'remnux-'
    libvirt.driver = 'kvm'
    libvirt.memory = '1024'
    libvirt.cpus = 1
    libvirt.sound_type = nil
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'telnet::4421,server,nowait'
    libvirt.random model: 'random'
  end

  config.vm.provision 'remnux-install', type: 'shell', name: 'remnux-install', inline: <<-SHELL
    sudo apt update &&\
      sudo apt upgrade -y
    sudo apt install -y gnupg
    cd ~ &&\
      mkdir remnux-install &&\
      wget https://REMnux.org/remnux-cli
    SHA256=$(sha256sum remnux-cli)
    if [ ! $SHA256 = 8193df477c0e0f14b53d018db141b969ab48f8da550384ef6d6e51482ebdda9d ];then exit 1;fi
    mv remnux-cli remnux &&\
      chmod +x remnux &&\
      sudo mv remnux /usr/local/bin
    sudo remnux install
  SHELL

  config.vm.provision :reload
end
