# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
MOUNT_POINT = '/home/vagrant/ff'
CPU_COUNT = 2
MEMORY = 512

Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/freebsd14'
  config.vm.box_version = '4.3.12'
  config.vm.box_check_update = false
  config.vm.synced_folder './', MOUNT_POINT, type: 'nfs', nfs_version: 4, nfs_udp: false
  config.vm.hostname = 'freebsd13'
  config.vm.boot_timeout = 240
  config.vm.graceful_halt_timeout = 45

  # config.vagrant.plugins = [{ 'vagrant-libvirt' => { 'version' => '^0.6.2' } }]

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = CPU_COUNT
    vb.gui = false
    vb.memory = MEMORY.to_s
  end
  config.vm.provider 'libvirt' do |libvirt|
    libvirt.default_prefix = 'freebsd14-'
    libvirt.driver = 'kvm'
    libvirt.nested = false
    # libvirt.qemuargs value: '-object'
    # libvirt.qemuargs value: 'rng-random,id=rng0,filename=/dev/urandom'
    # libvirt.qemuargs value: '-device'
    # libvirt.qemuargs value: 'virtio-rng-pci,rng=rng0,bus=pcie.0'
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'pty'
    libvirt.sound_type = nil
    libvirt.cpus = CPU_COUNT
    libvirt.memory = MEMORY
    libvirt.random model: 'random'
    libvirt.autostart = false
  end

  config.vm.provision 'provision', type: 'shell', name: 'provision', privileged: false, reboot: false, inline: <<-SHELL
    set -ex
    sudo pkg update && sudo pkg upgrade -y
    sudo pkg install -y pkgconf gcc gmake git wget curl vim tmux ncurses readline
  SHELL
end
