# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/debian11'
  config.vm.box_version = '4.0.4'
  config.vm.box_check_update = false
  config.vm.hostname = 'virt-deb11'

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  config.vm.network 'forwarded_port', guest: 7070, host: 7070, protocol: 'tcp', atuo_correct: true
  config.vm.network 'forwarded_port', guest: 4444, host: 4444, protocol: 'tcp', atuo_correct: true
  config.vm.network 'forwarded_port', guest: 4447, host: 4447, protocol: 'tcp', atuo_correct: true
  # config.vm.network 'forwarded_port', guest: 7070, host: 7070, protocol: 'tcp', host_ip: '192.168.1.103'
  # config.vm.network 'forwarded_port', guest: 4444, host: 4444, protocol: 'tcp', host_ip: '192.168.1.103'
  # config.vm.network 'forwarded_port', guest: 4447, host: 4447, protocol: 'tcp', host_ip: '192.168.1.103'

  # shares
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 4, nfs_udp: false

  config.vagrant.plugins = ['vagrant-reload', { 'vagrant-libvirt' => { 'version' => '^0.6.2' } }]

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.default_prefix = 'deb11-'
    libvirt.driver = 'kvm'
    libvirt.memory = '2048'
    libvirt.cpus = 2
    libvirt.sound_type = nil
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'serial,path=/dev/ttyS0,id=hostusbserial'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'pci-serial,chardev=hostusbserial'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'telnet::4321,server,nowait'
    libvirt.random model: 'random'
  end

  # config.vm.provision 'i2p-install', type: 'shell', name: 'i2p-install', inline: <<-SHELL
  #   export DEBIAN_FRONTEND=noninteractive && \
  #     sudo apt update && sudo apt upgrade -y && \
  #     sudo apt install -y firefox-esr
  #   # sudo apt install -y i2p i2p-router
  #   # i2prouter start
  # SHELL
end
