# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/rhel7'
  config.vm.box_version = '4.0.2'
  config.vm.box_check_update = false
  config.vm.hostname = 'virt-rhel7'

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  if Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.http = 'socks5://192.168.1.103:9050'
    config.proxy.https = 'socks5://192.168.1.103:9050'
    # config.proxy.noproxy = '127.0.0.1, localhost'
  end

  # shares
  # config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 3, nfs_udp: false

  config.vagrant.plugins = ['vagrant-reload', { 'vagrant-libvirt' => { 'version' => '^0.6.2' } }]

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.default_prefix = 'rhel7-'
    libvirt.driver = 'kvm'
    libvirt.memory = '512'
    libvirt.cpus = 1
    libvirt.sound_type = nil
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'serial,path=/dev/ttyS0,id=hostusbserial'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'pci-serial,chardev=hostusbserial'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'telnet::4339,server,nowait'
    libvirt.random model: 'random'
  end

  # config.vm.provision 'i2p-install', type: 'shell', name: 'i2p-install', inline: <<-SHELL
  #   sudo apt update && sudo apt upgrade -y
  # SHELL
end
