# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'alpine-3.22-amd64'
  # config.vm.box_version = '4.3.12'
  config.vm.box_check_update = false
  config.vm.hostname = 'virt-wg-zrh'

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  # shares
  # config.vm.synced_folder './share', '/home/vagrant/nfs', type: 'nfs', nfs_version: 4, nfs_udp: false

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.autostart = true
    libvirt.default_prefix = 'mullvad-wg-zrh-'
    libvirt.driver = 'kvm'
    libvirt.memory = '256'
    libvirt.cpus = 1
    libvirt.sound_type = nil
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'pty'
    # libvirt.random model: 'random'
  end

  config.vm.provision 'update', type: 'shell', name: 'update', inline: <<-SHELL
    set -ex
    sudo apk update && sudo apk upgrade
    sudo apk add nfs-utils wireguard-tools-wg-quick iptables ip6tables curl
    mkdir -p /vagrant && \
      sudo mount -t nfs 192.168.121.1:/home/devi/share/nfs /vagrant
  SHELL

  config.vm.provision 'update-root', type: 'shell', name: 'update-root', privileged: true, inline: <<-SHELL
    set -ex
    echo tun >> /etc/modules

    mkdir -p /etc/wireguard
    cp /vagrant/mullvad_wg/ch-zrh-wg-401.conf /etc/wireguard/wg0.conf

    echo "auto wg0" >> /etc/network/interfaces
    echo "iface wg0" inet static >> /etc/network/interfaces
    echo "pre-up wg-quick up" /etc/wireguard/wg0.conf >> /etc/network/interfaces

    modprobe tun
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/ipv4.conf
    sysctl -p /etc/sysctl.d/ipv4.conf

    wg-quick up wg0
  SHELL

  # config.vm.provision 'killswitch', type: 'shell', name: 'killswitch', privileged: true, inline: <<-SHELL
  #   set -ex
  #   ufw --force reset
  # SHELL
end
