# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
MOUNT_POINT = '/home/vagrant/ff'
CPU_COUNT = 1
MEMORY = 128

Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/openbsd7'
  config.vm.box_version = '4.3.12'
  config.vm.box_check_update = false
  config.vm.synced_folder './', MOUNT_POINT, type: 'nfs', nfs_version: 3, nfs_udp: false, disabled: true
  config.vm.hostname = 'openbsd7'
  config.vm.boot_timeout = 240
  config.vm.graceful_halt_timeout = 45

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.default_prefix = 'openbsd7-'
    libvirt.driver = 'kvm'
    libvirt.nested = false
    libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'pty'
    libvirt.sound_type = nil
    libvirt.cpus = CPU_COUNT
    libvirt.memory = MEMORY
    libvirt.random model: 'random'
    libvirt.autostart = false
  end

  # config.vm.provision 'provision', type: 'shell', name: 'provision', privileged: false, reboot: false, inline: <<-SHELL
  #   sudo pkg update && sudo pkg upgrade -y
  #   sudo pkg install -y pkgconf gcc gmake git wget curl vim tmux ncurses readline
  # SHELL
end
