# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

  config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
   end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update && sudo apt upgrade -y
    sudo apt install -y ksh wget curl vim tmux apt-file git python3 python3-pip
    sudo apt-file update
    echo "set -g default-terminal screen-256" > ~/.tmux.conf
  SHELL
end
