# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

  config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
   end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo dnf update
  #   sudo dnf install -y vim make cmake ninja-build meson gcc tmux wget curl git
  #   sudo dnf install -y python3-pyelftools
  #   sudo dnf groupinstall "Development Tools"
  #   sudo dnf install libpcap-devel zlib-devel libfdt-devel openssl-devel
  #   sudo modprobe vfio-pci
  # SHELL
end
