# vi: set ft=ruby :
# frozen_string_literal: true

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.require_version '>= 2.2.6'
Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2204'
  config.vm.box_version = '4.0.0'
  config.vm.box_check_update = false
  config.vm.hostname = 'virt-dispffox'

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  # shares
  # config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: 4, nfs_udp: false

  # config.vagrant.plugins = ['vagrant-reload', { 'vagrant-libvirt' => { 'version' => '^0.6.2' } }]

  config.vm.provider 'libvirt' do |libvirt|
    # libvirt.storage_pool_name = 'zpool'
    libvirt.default_prefix = 'dispffox-'
    libvirt.driver = 'kvm'
    libvirt.memory = '4096'
    libvirt.cpus = 4
    libvirt.sound_type = nil
    # libvirt.qemuargs value: '-nographic'
    libvirt.qemuargs value: '-nodefaults'
    libvirt.qemuargs value: '-no-user-config'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'serial,path=/dev/ttyS0,id=hostusbserial'
    # libvirt.qemuargs value: '-chardev'
    # libvirt.qemuargs value: 'pci-serial,chardev=hostusbserial'
    libvirt.qemuargs value: '-serial'
    libvirt.qemuargs value: 'pty'
    libvirt.random model: 'random'
  end

  config.vm.provision 'ffox-install', type: 'shell', name: 'ffox-install', privileged: true , inline: <<-SHELL
    echo <<- HEREDOC > /etc/apt/apt.conf.d/proxy.conf
      Acquire::http::Proxy "socks5h://192.168.1.214:9995";
      Acquire::https::Proxy "socks5h://192.168.1.214:9995";
    HEREDOC
    echo <<- HEREDOC >> /etc/ssh/sshd_config
      X11DisplayOffset 0
      X11UseLocalhost no
    HEREDOC
  SHELL
  config.vm.provision 'ffox-install', type: 'shell', name: 'ffox-install', inline: <<-SHELL
    sudo apt update && sudo apt upgrade -y
    sudo snap install firefox
    sudo apt install -y xorg xauth
  SHELL
end
