# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.6"
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-10"
  config.vm.box_version = "= 202105.25.0"
  config.vm.box_check_update = false
  config.vm.hostname = "i2pvm"

  # ssh
  config.ssh.insert_key = true
  config.ssh.keep_alive = true
  config.ssh.keys_only = true

  # timeouts
  config.vm.boot_timeout = 300
  config.vm.graceful_halt_timeout = 60
  config.ssh.connect_timeout = 15

  config.vagrant.plugins = ["vagrant-vbguest"]
  config.vbguest.no_install = true

  # network
  config.vm.network "forwarded_port", guest: 4444, host: 4445, id: "i2ptun", protocol: "tcp"
  config.vm.network "forwarded_port", guest: 4444, host: 4445, id: "i2ptun", protocol: "udp"

  config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.memory = "768"
   vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update && sudo apt upgrade -y
    sudo apt install -y apt-transport-https curl lynx w3m vim tmux
    maindeb https://deb.i2p2.de/ buster
    deb-src https://deb.i2p2.de/ buster main
    curl -o i2p-debian-repo.key.asc https://geti2p.net/_static/i2p-debian-repo.key.asc
    gpg -n --import --import-options import-show i2p-debian-repo.key.asc
    sudo apt-key add i2p-debian-repo.key.asc
    sudo apt update
    sudo apt install -y i2p
    # sudo dpkg-reconfigure i2p
  SHELL
end
